### ISSUE TITLE
Request for support for BabaSSL/Tongsuo 

### ISSUE THREAD

**Issue by MarcoMarcoaldi** [nginx-quic/nginx-quic#1]
I am writing to request support regarding the compilation with the http3 module enabled using BabaSSL/Tongsuo as a leaner and faster solution in TLS handshake negotiation. I have learned from reputable sources, including AliBaba developers, that this solution can save about 80% of time in TLS handshake negotiation.

However, I am experiencing some issues during compilation with the http3 module enabled, which is preventing the use of this solution. Would it be possible to provide me with some guidance on how to resolve this issue?

Thank you in advance for your attention, and I look forward to hearing from you soon.

**Comment by zengxs** [comment]
Hi @MarcoMarcoaldi,

Thank you for leaving a message on the nginx-quic repository. However, I would like to inform you that this repository is not an official mirror and I am not affiliated with the nginx development team. Thus, I am unable to provide you with any assistance on nginx development.

I would suggest that you seek help from the official nginx forums or mailing lists instead, where you can connect with experienced developers and get the help you need.

Thank you for your understanding.

Best regards,
Xiangsong Zeng
