### ISSUE TITLE
Will new quic connections be handled by old workers?

### ISSUE THREAD

**Issue by haiyyang** [nginx-quic/nginx-quic#2]
I wonder if the problem have been solved.
Can the current nginx-quic handle HTTP3 traffic smoothly when reload/upgrade?
refer to https://forum.nginx.org/read.php?29,290936,290938

**Comment by zengxs** [comment]
Apologies for any confusion, but I must inform you that this is an unofficial mirror and I am not in a position to provide a answer to your question.

I recommend that you reach out to the official forum or email list for the necessary assistance.

Thank you for your understanding.

**Comment by haiyyang** [comment]
ok， understood, thanks for you answer
